// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyHangHoa.Data;

#nullable disable

namespace QuanLyHangHoa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260520084619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("QuanLyHangHoa.Models.HangHoa", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaNCC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MaHang");

                    b.HasIndex("MaNCC");

                    b.HasIndex("TenHang")
                        .IsUnique();

                    b.ToTable("HangHoas");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MaNCC");

                    b.HasIndex("TenNCC")
                        .IsUnique();

                    b.ToTable("NhaCungCaps");

                    b.HasData(
                        new
                        {
                            MaNCC = 1,
                            DiaChi = "123 Nguyễn Huệ, TP.HCM",
                            DienThoai = "0901234567",
                            TenNCC = "Công ty TNHH A"
                        },
                        new
                        {
                            MaNCC = 2,
                            DiaChi = "456 Lê Lợi, Hà Nội",
                            DienThoai = "0912345678",
                            TenNCC = "Công ty TNHH B"
                        },
                        new
                        {
                            MaNCC = 3,
                            DiaChi = "789 Trần Hưng Đạo, Đà Nẵng",
                            DienThoai = "0923456789",
                            TenNCC = "Công ty TNHH C"
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.HangHoa", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.NhaCungCap", b =>
                {
                    b.Navigation("HangHoas");
                });
#pragma warning restore 612, 618
        }
    }
}
